---
version: '3'
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /path/library:/config
      - /path/tvseries:/tv
      - /path/movies:/movies
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /path/qbit/appdata/config:/config
      - /path:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    volumes:
      - /path/file/:/srv
      - /path/file/filebrowser.db:/database.db #must be created before first start
      - /path/file/.filebrowser.json:/.filebrowser.json
    ports:
      - 80:80 
    restart: unless-stopped
    security-opt:
      - no-new-privileges: true